name: Tests (Python)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: 'fake-secret'
      DEBUG: true
      ALLOWED_HOSTS: "*"
      DATABASE_URL: postgres://db_user:db_pwd@db:5432/db_name
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pwd
      POSTGRES_DB: db_name
      BROKER_URL: redis://redis:6379/0
      RESULT_URL: redis://redis:6379/1
      SOCIAL_AUTH_GITHUB_KEY: ---
      SOCIAL_AUTH_GITHUB_SECRET: ---
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Run tests
        run: |
          python ./manage.py test -v 2
